version: "3"

services:
  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 101202
      MYSQL_DATABASE: checkpoint2dockercompose
      MYSQL_USER: rm95749
      MYSQL_PASSWORD: 101202
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - checkpoint2dockercompose_network

  app:
    container_name: checkpoint2dockercompose
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: checkpoint2dockercompose
      DB_USER: rm95749
      DB_PASSWORD: 101202
      AUTH_PLUGIN: mysql_native_password
    depends_on:
      - db
    networks:
      - checkpoint2dockercompose_network

volumes:
  db_data:

networks:
  checkpoint2dockercompose_network:
    driver: bridge
